
spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8082
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    check: false # 启动时不检查服务提供者是否存在